<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Eval Output</title>
    <style>
      body {
        font-family:
          -apple-system,
          BlinkMacSystemFont,
          Segoe UI,
          Roboto,
          Helvetica,
          Arial,
          sans-serif;
      }
      table,
      th,
      td {
        border: 1px solid black;
        border-collapse: collapse;
        text-align: left;
        word-break: break-all;
      }
      th,
      td {
        padding: 5px;
        min-width: 200px;
        white-space: pre-line;
        vertical-align: top;
      }

      tr > td[data-content^='[PASS]'] {
        color: green;
      }
      tr > td[data-content^='[FAIL]'] {
        color: #ad0000;
      }
    </style>
  </head>
  <body>
    <table>
      <thead>
        
        <th>messages</th>
        
        <th>system_message</th>
        
        <th>question</th>
        
        <th>[Chatbot Python script] gpt_chat_prompt: prompts/prompt.txt: You're an ecommerce chat assistant for a shoe shop.
Answer this user's question: {{name}}: "{{question}}"</th>
        
        <th>[Chatbot Python script] gpt_chat_prompt: prompts/prompt.txt: You're a smart, bubbly chat assistant for a shoe shop.
Answer this user's question: {{name}}: "{{question}}"</th>
        
      </thead>
      <tbody>
        
        <tr>
          
          <td data-content="[{&quot;user&quot;:&quot;How do I track my order?&quot;},{&quot;assistant&quot;:&quot;You can track your order by clicking on the &#92;&quot;Track Order&#92;&quot; link in the order confirmation email or by logging into your account on our website and navigating to the &#92;&quot;Orders&#92;&quot; section.&quot;},{&quot;user&quot;:&quot;Give me shipping info&quot;},{&quot;assistant&quot;:&quot;Shipping Options: - Standard Shipping (5-7 business days) - Expedited Shipping (2-3 business days) - Next-Day Shipping (1 business day)&quot;}]">[{"user":"How do I track my order?"},{"assistant":"You can track your order by clicking on the \"Track Order\" link in the order confirmation email or by logging into your account on our website and navigating to the \"Orders\" section."},{"user":"Give me shipping info"},{"assistant":"Shipping Options: - Standard Shipping (5-7 business days) - Expedited Shipping (2-3 business days) - Next-Day Shipping (1 business day)"}]</td>
          
          <td data-content="Answer concisely">Answer concisely</td>
          
          <td data-content="Tell me about faqs about payment methods">Tell me about faqs about payment methods</td>
          
          <td data-content="[FAIL] (0.00)

  Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)
---
Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)">[FAIL] (0.00)

  Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)
---
Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)</td>
          
          <td data-content="[FAIL] (0.00)

  Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)
---
Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)">[FAIL] (0.00)

  Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)
---
Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)</td>
          
        </tr>
        
        <tr>
          
          <td data-content="[{&quot;user&quot;:&quot;How do I track my order?&quot;},{&quot;assistant&quot;:&quot;You can track your order by clicking on the &#92;&quot;Track Order&#92;&quot; link in the order confirmation email or by logging into your account on our website and navigating to the &#92;&quot;Orders&#92;&quot; section.&quot;},{&quot;user&quot;:&quot;Give me shipping info&quot;},{&quot;assistant&quot;:&quot;Shipping Options: - Standard Shipping (5-7 business days) - Expedited Shipping (2-3 business days) - Next-Day Shipping (1 business day)&quot;}]">[{"user":"How do I track my order?"},{"assistant":"You can track your order by clicking on the \"Track Order\" link in the order confirmation email or by logging into your account on our website and navigating to the \"Orders\" section."},{"user":"Give me shipping info"},{"assistant":"Shipping Options: - Standard Shipping (5-7 business days) - Expedited Shipping (2-3 business days) - Next-Day Shipping (1 business day)"}]</td>
          
          <td data-content="Answer concisely">Answer concisely</td>
          
          <td data-content="Tell me about order process?">Tell me about order process?</td>
          
          <td data-content="[FAIL] (0.00)

  Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)
---
Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)">[FAIL] (0.00)

  Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)
---
Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)</td>
          
          <td data-content="[FAIL] (0.00)

  Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)
---
Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)">[FAIL] (0.00)

  Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)
---
Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)</td>
          
        </tr>
        
        <tr>
          
          <td data-content="[{&quot;user&quot;:&quot;How do I track my order?&quot;},{&quot;assistant&quot;:&quot;You can track your order by clicking on the &#92;&quot;Track Order&#92;&quot; link in the order confirmation email or by logging into your account on our website and navigating to the &#92;&quot;Orders&#92;&quot; section.&quot;},{&quot;user&quot;:&quot;Give me shipping info&quot;},{&quot;assistant&quot;:&quot;Shipping Options: - Standard Shipping (5-7 business days) - Expedited Shipping (2-3 business days) - Next-Day Shipping (1 business day)&quot;}]">[{"user":"How do I track my order?"},{"assistant":"You can track your order by clicking on the \"Track Order\" link in the order confirmation email or by logging into your account on our website and navigating to the \"Orders\" section."},{"user":"Give me shipping info"},{"assistant":"Shipping Options: - Standard Shipping (5-7 business days) - Expedited Shipping (2-3 business days) - Next-Day Shipping (1 business day)"}]</td>
          
          <td data-content="Answer concisely">Answer concisely</td>
          
          <td data-content="Please provide me shipping info. My order number is 111-9244735-1237858 and my email address is john@mail.com">Please provide me shipping info. My order number is 111-9244735-1237858 and my email address is john@mail.com</td>
          
          <td data-content="[FAIL] (0.00)

  Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)
---
Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)">[FAIL] (0.00)

  Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)
---
Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)</td>
          
          <td data-content="[FAIL] (0.00)

  Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)
---
Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
Stack Trace: Error: AttributeError: module &#39;chatbot_wrapper&#39; has no attribute &#39;call_api&#39;
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.&lt;anonymous&gt; (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 35, in &lt;module&gt;
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File &quot;/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py&quot;, line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)">[FAIL] (0.00)

  Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)
---
Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Error running Python script: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
Stack Trace: Error: AttributeError: module 'chatbot_wrapper' has no attribute 'call_api'
at PythonShell.parseError (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:303:21)
at terminateIfNeeded (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:193:32)
at Socket.<anonymous> (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/python-shell/index.js:173:17)
at Socket.emit (node:events:532:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
--Python Traceback: --
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 35, in <module>
  result = call_method(script_path, method_name, *data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/wrapper.py", line 20, in call_method
  method_to_call = getattr(script_module, method_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at runPython (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/python/pythonUtils.js:117:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PythonProvider.executePythonScript (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:54:31)
at async Evaluator.runEval (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:170:28)
at async processEvalStep (/Users/ningo/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:527:25)</td>
          
        </tr>
        
      </tbody>
    </table>
  </body>
</html>
